# Site setings
name: 'Shris-T'
description: 'I am a bioinformatics analyst and staff scientist at Creative Data Solutions, Vanderbilt University'
meta_description: 'I am a bioinformatics analyst and staff scientist at Creative Data Solutions, Vanderbilt University, that provides bioinformatics and informatics research services (https://cds.vanderbilt.edu/). My interest in biological data analysis has lead me to enjoy bulk and single cell RNA-seq analysis space mostly but also currently keen on software development, data science and creative data visual projects '
greetings: 'Shristi Shrestha'
logo:
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://shristi-shrestha.github.io/
disqus: 'Shris-T'
mailchimp_url: ''
cover_image: covers/fal2021.jpeg
# Add your GA Tracking Id
ga_analytics: 

# Contact form setings
email: shres.shristi@gmail.com
contact_page_description: ""
thankyou_page_description: "Your message has been successfully sent. I will contact you very soon!"

# Social links
twitter: 'shr9st9'
github: 'shristi-shrestha'
linkedin: 'shristi-shrestha'


# Navigation
navigation:
  - text: About
    url: /about
  - text: Style Guide
    url: /style-guide
  - text: Contact Me
    url: /contact

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 7
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
